### ISSUE TITLE
Make Error

### ISSUE THREAD

**Issue by nambiarshiva** [FlorianWestphal/VMI-PL#1]
netlink_kernel_create function only has three argument but in two cases 6 arguments have been passed. My make fails due to this error. links :  vmx.c - https://pastebin.com/fAAAc9Lh,
netlink.h - https://pastebin.com/cK1pe0BN,
vmi_pl.h - https://pastebin.com/uUv5raer

![er](https://user-images.githubusercontent.com/12592385/31574660-88c11cd6-b0f1-11e7-8565-3dcacda46f0f.png)

**Comment by FlorianWestphal** [comment]
It seems that you are using the wrong Linux kernel version (the code was tested on Linux kernel 3.2). According to stackoverflow [1], the function signature for netlink_kernel_create changed with Linux kernel 3.8. Therefore, you can either change to the supported kernel version or modify vmx.c to use the correct function signature. 
I have attached a patch, which can be applied to the vmx.c version, which was patched using vmipl.patch. Just navigate to the location of vmx.c and run: patch < <path to new patch>/netlink_kernel_create.patch
However, while this should solve the problem with netlink_kernel_create, I have not tested this patch and you might run into other issues.

[1] - https://stackoverflow.com/questions/15937395/netlink-kernel-create-is-not-working-with-latest-linux-kernel

[netlink_kernel_create.patch.txt](https://github.com/FlorianWestphal/VMI-PL/files/1405046/netlink_kernel_create.patch.txt)

**Comment by nambiarshiva** [comment]
I did rollback back my kernel to 3.2.0-126 but now another error persists in svm.c file 
svm.c : https://pastebin.com/GATcf0dT
![err](https://user-images.githubusercontent.com/12592385/32263738-2ebcd28e-bf01-11e7-8fa1-b7b67da401f9.png)
